- name: Esempio di task con valore di ritorno
  set_fact:
    my_variable: " valore di RETURN "
- debug:
    msg: "{{ my_variable }}."

 #esempio look up --mpstra  il contenutoi del file ciao 
- name: Leggi il file Ciao
  ansible.builtin.debug:
    msg: "{{ lookup('file', 'Esercizio1/roles/common/files/ciao') }}"


- name: group1.yml
  include_vars:
    file: Esercizio1/groups_vars/group1.yml
- name: stampa valore variabile
  debug:
    var: group_var1